# Generated by Django 2.1.5 on 2019-04-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuralnetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weights',
            name='file',
            field=models.CharField(max_length=2000),
        ),
    ]
