# Generated by Django 2.1.5 on 2019-04-20 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neuralnetwork', '0003_auto_20190417_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='weights',
            name='weight',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weights',
            name='file',
            field=models.FileField(upload_to='aftertrained/'),
        ),
    ]
